### PR TITLE
Removed TIM Support

### PR DESCRIPTION
**Pull request by dmccoystephenson**
## Problem
Although the PPM currently supports processing TIMs, this isn't part of the data flow to RSUs and the SDX. Filtered TIMs are stored in a topic for potential future use. The only relevant filtering for TIMs is geofence-based. Additionally, there is no personally identifiable information to redact in TIMs. Therefore, support for processing TIMs should be removed.
## Solution
All references to TIMs have been removed from the project.

## Testing
- The `do_kafka_test.sh` script has been verified to work with these changes.
- The unit tests pass.
- The program spins up correctly.

## Dependent PR
The `refactoring/remove-tim-references` branch was created using `docs/supported-message-types` as a base, the PR for which should be merged first: https://github.com/CDOT-CV/jpo-cvdp/pull/44

### CODE REVIEW

**Review by Michael7371 — CHANGES_REQUESTED** [review]
I am having issues with the `do_kafka_test.sh` test script. Here is the output of the script:

```
$ ./do_kafka_test.sh 

Step 1/5: Set up test environment
=== Setup Info ===
DOCKER_HOST_IP: 192.168.170.53
KAFKA_CONTAINER_NAME is resolved dynamically
MAP_FILE: data/I_80.edges
BSM_DATA_FILE: data/I_80_test.json
PPM_CONTAINER_NAME: test_ppm_instance
PPM_IMAGE_TAG: do-kafka-test-ppm-image
PPM_IMAGE_NAME: jpo-cvdp_ppm
==================
WARN[0000] /mnt/c/Users/michael/Documents/GitHub/cdot-jpo-cvdp/docker-compose-kafka.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] /mnt/c/Users/michael/Documents/GitHub/cdot-jpo-cvdp/docker-compose-kafka.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 3/3
 ✔ Network cdot-jpo-cvdp_default        Created                                                                                                                  0.0s 
 ✔ Container cdot-jpo-cvdp-kafka-1      Started                                                                                                                  0.5s 
 ✔ Container cdot-jpo-cvdp-zookeeper-1  Started                                                                                                                  0.5s 

Step 2/5: Wait for Kafka to create topics
Kafka has created all required topics

Step 3/5: Build PPM image
[+] Building 1.3s (23/23) FINISHED                                                                                                                     docker:default
 => [internal] load build definition from Dockerfile.testing                                                                                                     0.1s
 => => transferring dockerfile: 1.49kB                                                                                                                           0.0s 
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                                                   0.1s 
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 18)                                                                                  0.1s 
 => [internal] load metadata for docker.io/library/alpine:3.12                                                                                                   0.6s 
 => [internal] load .dockerignore                                                                                                                                0.1s
 => => transferring context: 2B                                                                                                                                  0.0s 
 => [internal] load build context                                                                                                                                0.5s 
 => => transferring context: 8.18kB                                                                                                                              0.5s 
 => [runtime-deps 1/4] FROM docker.io/library/alpine:3.12@sha256:c75ac27b49326926b803b9ed43bf088bc220d22556de1bc5f72d742c91398f69                                0.0s 
 => CACHED [runtime-deps 2/4] WORKDIR /cvdi-stream                                                                                                               0.0s
 => CACHED [runtime-deps 3/4] RUN apk update                                                                                                                     0.0s 
 => CACHED [runtime-deps 4/4] RUN apk add --upgrade --no-cache     bash     python3     librdkafka     librdkafka-dev                                            0.0s 
 => CACHED [builder  1/10] WORKDIR /cvdi-stream                                                                                                                  0.0s 
 => CACHED [builder  2/10] RUN apk add --upgrade --no-cache --virtual .build-deps     cmake     g++     make                                                     0.0s 
 => CACHED [builder  3/10] ADD CMakeLists.txt /cvdi-stream                                                                                                       0.0s 
 => CACHED [builder  4/10] ADD ./src /cvdi-stream/src                                                                                                            0.0s 
 => CACHED [builder  5/10] ADD ./cv-lib /cvdi-stream/cv-lib                                                                                                      0.0s 
 => CACHED [builder  6/10] ADD ./include /cvdi-stream/include                                                                                                    0.0s 
 => CACHED [builder  7/10] ADD ./kafka-test /cvdi-stream/kafka-test                                                                                              0.0s 
 => CACHED [builder  8/10] ADD ./unit-test-data /cvdi-stream/unit-test-data                                                                                      0.0s 
 => CACHED [builder  9/10] ADD ./config /cvdi-stream/config                                                                                                      0.0s 
 => CACHED [builder 10/10] RUN export LD_LIBRARY_PATH=/usr/local/lib && mkdir /cvdi-stream-build && cd /cvdi-stream-build && cmake /cvdi-stream && make          0.0s 
 => CACHED [stage-2 2/5] COPY --from=builder /cvdi-stream-build/ /cvdi-stream-build/                                                                             0.0s
 => CACHED [stage-2 3/5] COPY --from=builder /cvdi-stream /cvdi-stream                                                                                           0.0s 
 => CACHED [stage-2 4/5] ADD ./docker-test /cvdi-stream/docker-test                                                                                              0.0s 
 => CACHED [stage-2 4/5] ADD ./docker-test /cvdi-stream/docker-test                                                                                              0.0s   
 => CACHED [stage-2 5/5] RUN chmod 777 /cvdi-stream/docker-test/ppm_no_map.sh                                                                                    0.0s
 => exporting to image                                                                                                                                           0.0s
 => => exporting layers                                                                                                                                          0.0s
 => => writing image sha256:a7aa33774f7945f8fb0cf885847f0da2e27d50aec3a12e45a8b268aa6cd7e3cf                                                                     0.0s
 => => naming to docker.io/library/jpo-cvdp_ppm:do-kafka-test-ppm-image                                                                                          0.0s

 2 warnings found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 18)

Step 4/5: Run tests
--- File Being Used ---
data/I_80.edges
data/I_80_test.json
-----------------
Test 1/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c1.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
4caf174ff0d6e15b7a5d4f8b7b9d45c6d1e097ab82a084c43799705bdba39a41
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 0 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'


Test 2/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c2.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
4db58fa60c2fbf63dab45a13f4f3cfca94c92d495b4638048c7bb65339253ab4
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 10 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'
^CPost "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/test_ppm_instance/stop": context canceled


Test 3/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c3.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
708f468979f549dc983d2d5c4847b3addf0cd18ca6c693f56c16c95b46accb89
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 18 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'


Test 4/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c4.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
635286712e5efd8b985b57e2a8ddaa76376227f3abca1a81c4f3e0685a9725b6
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 23 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'


Test 5/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c5.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
6f7cb051cce19a3eb2bb273f4814f50b21b20bc774b31237668a16d7e61365f1
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 33 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'


Test 6/6
**************************
Running standalone test in test_ppm_instance container with data/I_80.edges config/bsm-test/c6.properties data/I_80_test.json
**************************
Error response from daemon: No such container: test_ppm_instance
Starting PPM in new container 'test_ppm_instance'
370504d79bc4bc8c4c93c1be997b50c83d4890fb57b710441e7dfc2cf7211a29
Waiting for test_ppm_instance to spin up
test_ppm_instance is ready after 32 seconds
**************************
Producing Raw BSMs...
**************************
': No such file or directory
**************************
Consuming Filtered BSMs at offset 43 ...
**************************
': No such file or directory
Error: Kafka consumer timed out.
~~~~~~~~~~~~~~~~~~~~~~~~~~
TEST FAILED!
~~~~~~~~~~~~~~~~~~~~~~~~~~
Stopping existing PPM container 'test_ppm_instance'



Step 5/5: Cleanup
[log] stopping Kafka
WARN[0000] /mnt/c/Users/michael/Documents/GitHub/cdot-jpo-cvdp/docker-compose-kafka.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 3/3
 ✔ Container cdot-jpo-cvdp-kafka-1      Removed                                                                                                                                                                                                                                                                                                                6.0s 
 ✔ Container cdot-jpo-cvdp-zookeeper-1  Removed                                                                                                                                                                                                                                                                                                               10.3s 
 ✔ Network cdot-jpo-cvdp_default        Removed
 ```

**Review by mwodahl — COMMENTED** [review]
These changes look good to me and unit tests pass! There is one lingering TIM reference in standalone.sh on line 6 but that was the only reference I could find.

**Comment by dmccoystephenson** [comment]
> I am having issues with the `do_kafka_test.sh` test script. Here is the output of the script:
> 

I'm not running into that error on my machine. That's interesting.

**Comment by dmccoystephenson** [comment]
> These changes look good to me and unit tests pass! There is one lingering TIM reference in standalone.sh on line 6 but that was the only reference I could find.

Removed!

**Review by mwodahl — APPROVED** [review]
Looks good to me!

**Review by Michael7371 — APPROVED** [review]
Tests pass now and I like the changes!

**Pull request merged**
